### ISSUE TITLE
mfcc mean and std and 

### ISSUE THREAD

**Issue by Dannynis** [cjerry1243/TransferLearning-CLVC#1]
Hey, i'm very impressed by the results you've reached and currently trying to reproduce them on my own data
set with 2 speakers for now using files sampled at 16k (which doesnt suppose to matter because librosa upsamples them)
3 issues ive incountred are that the mfcc is normalized by mean and std that are unresolved,
also the program tries to load a ppg checkpoint that is not exist in the ppg folder i.e(352 instead of 142 )
also for some reason the ppg's shape[0] (numbers of frames) was greater then mel_24k, which resulted-
           " if mel_24k.shape[0] != ppg.shape[0]: " to accrue .
may you please help me to handle those issues ?

thank you and best regards 👍

**Comment by cjerry1243** [comment]
Thanks. 
I made a push to resolve the first 2 issues.

I guess the 3rd issue comes from your change in sampling rate. In preprocessing mel, the resampling is not applied.
I would recommend you resample and save the audio files before you start preprocessing, or if you really want a 16k version, change the config json file to fit your datasets. The step size, especially, is the key factor in determining the length of mel.

**Comment by Dannynis** [comment]
Thank you very much !
